### ISSUE TITLE
missing texture

### ISSUE THREAD

**Issue by FGDATA** [FGMEMBERS/pc7#2]
osgDB ac3d reader: could not find texture "Strobe.png"

@ehofman9923 
there's a missing texture file. Maybe you missed to push?

@IAHM-COL

**Comment by adalinbv** [comment]
On 06/15/2016 04:35 PM, FGDATA wrote:

> osgDB ac3d reader: could not find texture "Strobe.png"
> 
> @ehofman9923 https://github.com/ehofman9923
> there's a missing texture file. Maybe you missed to push?

No it's not about forgetting to push a texture. In fact it's right where 
it belongs. It's one of those things I have to figure out yet.

Erik

## 

http://www.adalin.com - High performance virtual reality audio software.

**Comment by IAHM-COL** [comment]
can you give me a pointer to the file? I searched for it with no success.

**Comment by adalinbv** [comment]
On 06/15/2016 11:53 PM, Israel Hernandez wrote:

> can you give me a pointer to the file? I searched for it with no success.

Ah wait, it was Halos.png bnut last time I checked both files where the 
same so I removed one of them but forgot to change the corresponding .ac 
file.

it might be worth some more investigation though.

Erik

## 

http://www.adalin.com - High performance virtual reality audio software.

**Comment by FGDATA** [comment]
![Halos](https://raw.githubusercontent.com/FGMEMBERS/pc7/master/Models/Lights/Halos.png)

That's how Halos looks like

I think it sounds fair to think this is also Strobe.png

**Comment by FGDATA** [comment]
@ehofman9923 

Once you are happy with the investigations, then merge to fix
https://github.com/FGMEMBERS/pc7/pull/3/files

Best,
@IAHM-COL

**Comment by adalinbv** [comment]
On 06/16/2016 12:34 AM, FGDATA wrote:

> @ehofman9923 https://github.com/ehofman9923
> 
> Once you are happy with the investigations, then merge to fix
> https://github.com/FGMEMBERS/pc7/pull/3/files

I had an older version of the pc7 which contained Light.png which turned 
out to be different than Halos.png so I added it back again.

Erik

## 

http://www.adalin.com - High performance virtual reality audio software.

**Comment by FGDATA** [comment]
fixed with https://github.com/FGMEMBERS/pc7/commit/9b3960fe786d935b9d59d6a150923f4c31136ada
